Feature/update backend
mirakst/P3-Project pull request #224
Opened 2021-12-14 08:50 UTC by damniko

- Moved all data parsing out of the (Dashboard)Controller and into separate Parser-classes
- DataUtilities has become an IDataHandler, which handles everything related to data in the system (and can easily be replaced by implementing the interface)
- And various back-end changes that make integration-testing possible, such as using an DbContextOptionsBuilder to create connection strings.
- Added integration tests (and unit tests for the new parser classes)
- Minor improvements such as maintaining the current selection in the Validation Report when new data is added

2021-12-14 10:04 UTC, Mthage20 commented on Model/Execution.cs
> +                    fucking.PerformanceScore = _managerScore.GetPerformanceScore(fucking);
fyha

2021-12-14 10:04 UTC, Mthage20 commented on Model/Execution.cs
> +                    fucking.ValidationScore = _managerScore.GetValidationScore(fucking);
elsker det her

2021-12-14 10:04 UTC, Mthage20 commented on Model/Network.cs
> +            : this()
Spørger ret dumt, men hvad er meningen med nedarvningen her?

2021-12-14 10:04 UTC, Mthage20 commented on Model/Conversion.cs
> +            return this;
Hmmm, hvor bliver denne return værdi brugt til noget? Jeg har lidt svært ved at gennemskue det :)

2021-12-14 10:04 UTC, Mthage20 commented on DashboardFrontend/ViewModels/ManagerViewModel.cs
> +            }
er det meningen, at ^M skal være der? (jeg kan ikke huske, hvad ^M er)

2021-12-14 10:04 UTC, Mthage20 commented on DashboardFrontend/ViewModels/ManagerObservable.cs
> +            OriginalManager = mgr;
Hvad/Hvor bliver OriginalManager brugt?

2021-12-14 10:04 UTC, Mthage20 commented on DashboardFrontend/Charts/Templates/NetworkDeltaChartTemplate.cs
> -                    MinLimit = 0,
Hvorfor var det nu, at min- og maxlimit blev fjernet?

2021-12-14 10:04 UTC, Mthage20 commented on DashboardFrontend/Charts/Templates/ChartTemplate.cs
> -        Performance, Network, NetworkDelta, NetworkSpeed
Hvorfor er det, at performance er blevet fjernet? Hvad har ændret sig, siden at den ikke længer skal være der?

2021-12-14 10:26 UTC, TorbjoernH approved these changes

2021-12-14 10:59 UTC, KasperHenningsen requested changes
nogele enkelte kommentare, men ellers wp

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend.Tests/HealthReportInfoParserTests.cs
> +        public List<HealthReportEntry> HostDataInput => new()
Ville det ikke være mere overskueligt at smide de her lister i en test data fil?

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend.Tests/NetworkReadingParserTests.cs
> +            var rnd = new Random(seed);
Tænk hvis vi havde brugt det i P2 xD

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend/DataHandler.cs
> +                    let content = Regex.Replace(item.LogMessage, @"\u001b\[\d*;?\d+m", "")
evt. tilføj en commentar om hvad den regex string gør

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend/DataHandler.cs
> +        ///
```suggestion
```

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend/DataHandler.cs
> +            return result;
```suggestion
            return _cpuReadingParser.Parse(data);
```

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend/DataHandler.cs
> +        }
eller
```suggestion
        public List<CpuLoad> GetParsedCpuReadings(List<HealthReportEntry> data) => _cpuReadingParser.Parse(data);
```

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend/DataHandler.cs
> +        }
igen
```suggestion
        public List<NetworkUsage> GetParsedNetworkReadings(List<HealthReportEntry> data)
        {
            return _networkReadingParser.Parse(data);
        }
```
eller
```suggestion
        public List<NetworkUsage> GetParsedNetworkReadings(List<HealthReportEntry> data) => _networkReadingParser.Parse(data);
```

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend/DataHandler.cs
> +        }
```suggestion
        public List<HealthReportEntry> GetHealthReportEntries(DateTime minDate)
        {
            return Database.QueryHealthReport(minDate);
        }
```

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardBackend/Settings/UserSettings.cs
> +        ///
Er det meningen at summery er tom?

2021-12-14 10:59 UTC, KasperHenningsen commented on DashboardFrontend/ViewModels/UserSettingsViewModel.cs
> +        }
Skal de her ikke gøre noget?

2021-12-14 10:59 UTC, KasperHenningsen commented on IntegrationTests/DashboardControllerTests.cs
> +    ////// NOTE: These tests require setup of a test database and a connectionstring in UserSecrets
hvad er UserSecrets?

2021-12-14 10:59 UTC, KasperHenningsen commented on Model/Execution.cs
> +
er det kun mig der ser "^M"?

2021-12-14 11:02 UTC, mirakst requested changes
godt arbejde hr.
har smidt nogle kommentarer

2021-12-14 11:02 UTC, mirakst commented on DashboardBackend/DataHandler.cs
> +        }
dokumentationen passer ikke helt

2021-12-14 11:02 UTC, mirakst commented on DashboardBackend/DataHandler.cs
> +        }
dokumentation passer ikke

2021-12-14 11:02 UTC, mirakst commented on DashboardBackend/DataHandler.cs
> +                healthReport.Ram = newData.Ram;
god ændring 👍

2021-12-14 11:02 UTC, mirakst commented on DashboardBackend/Database/IDatabase.cs
> +        List<HealthReportEntry> QueryHealthReport(DateTime minDate);
dokumentation outdated

2021-12-14 11:02 UTC, mirakst commented on DashboardBackend/DataHandler.cs
> +        }
hvordan kan det være at du ikke har brugt en parser her eller til validations?

2021-12-14 11:02 UTC, mirakst commented on DashboardBackend/Parsers/RamReadingParser.cs
> +        }
hmm, du kan lave den static, men hvorfor? jeg mindes at jeg har villet gøre det samme tidligere i projektet, hvor du ikke synes det var en god idé! desuden passer dokumentationen ikke helt

2021-12-14 11:02 UTC, mirakst commented on DashboardFrontend/DashboardController.cs
> +        public void UpdateLog()
den blev godt nok lang - måske kunne du opdatere dokumentationen så den fortæller lidt mere om hvad der sker

2021-12-14 11:02 UTC, mirakst commented on DashboardFrontend/ViewModels/ValidationReportViewModel.cs
> +            Executions = new(executions.ToList().Select(e => new ExecutionObservable(e, this)));
det her virker som en "collection was changed" safeguard - er lock ikke stærkt nok? (det tror jeg ikke nødvendivis selv, men vil gerne have dit input)

2021-12-14 11:02 UTC, mirakst commented on IntegrationTests/DashboardControllerTests.cs
> +}
det er bare godt benny

2021-12-14 11:02 UTC, mirakst commented on Model/Cpu.cs
> +
ruh roh the bad line endings

2021-12-14 11:02 UTC, mirakst commented on Model/Execution.cs
> +
her er den gal igen

2021-12-14 11:02 UTC, mirakst commented on Model/HealthReport.cs
> +        public bool IsInitialized => Ram?.Total is null; //If the health report has been built.
burde det ikke være "is not null"?

2021-12-14 11:02 UTC, mirakst commented on Model/Manager.cs
> +            UpdateValidationScore();
dokumentation

2021-12-14 11:10 UTC, damniko commented on DashboardBackend/Parsers/RamReadingParser.cs
> +        }
den kan også sagtens ikke være statisk - men der er forskel på at lave en hel klasse statisk, og at lave en privat hjælper-funktion statisk

2021-12-14 11:36 UTC, mirakst commented on DashboardBackend/Parsers/RamReadingParser.cs
> +        }
jaa, det handlede om en hjælper-funktion

2021-12-14 11:47 UTC, mirakst commented on DashboardFrontend/Charts/Templates/NetworkDeltaChartTemplate.cs
> -                    MinLimit = 0,
det er slet ikke en del af det her, men det er for at graf-viewet scaler med plots

2021-12-14 11:48 UTC, mirakst commented on DashboardFrontend/Charts/Templates/ChartTemplate.cs
> -        Performance, Network, NetworkDelta, NetworkSpeed
heller ikke en del af det her, egentlig bare fra noget andet, men det skyldes bare at det ikke blev brugt til noget alligevel

2021-12-14 12:44 UTC, AndersMariegaard commented on Model/Execution.cs
> +
Det er gits end-of-line character

2021-12-14 13:31 UTC, KasperHenningsen commented on Model/Execution.cs
> +
ja, men den laver new line hvis man merger det ind

2021-12-14 13:43 UTC, AndersMariegaard commented on DashboardBackend/Database/EntityFrameworkDb.cs
> -                                        ||  e.Key == "Skrevne rækker"))
Hvad er der sket med dem her? Parser?

2021-12-14 13:47 UTC, AndersMariegaard commented on DashboardFrontend/DashboardController.cs
> +        public void UpdateLog()
mother of god

2021-12-14 14:08 UTC, AndersMariegaard approved these changes

2021-12-14 15:08 UTC, damniko commented on DashboardBackend/Database/EntityFrameworkDb.cs
> -                                        ||  e.Key == "Skrevne rækker"))
jep

2021-12-14 15:08 UTC, damniko commented on Model/HealthReport.cs
> +        public bool IsInitialized => Ram?.Total is null; //If the health report has been built.
joe

2021-12-14 15:09 UTC, damniko commented on Model/Execution.cs
> +
det gitkraken

2021-12-14 15:10 UTC, damniko commented on DashboardBackend/DataHandler.cs
> +        }
well det kan jeg godt sætte op

2021-12-14 15:13 UTC, damniko commented on DashboardFrontend/ViewModels/ManagerObservable.cs
> +            OriginalManager = mgr;
Det er en begrænsning af at bruge viewmodels - vi vil stadig gerne kunne se managerens rows read/written, start/end times osv., og i stedet for at smide det ind i properties på den her ManagerObservable, så har vi bare en reference til den manager (og kan tilgå dens properties derigennem)

2021-12-14 15:14 UTC, damniko commented on DashboardBackend.Tests/HealthReportInfoParserTests.cs
> +        public List<HealthReportEntry> HostDataInput => new()
tvivler på at det er besværet værd - du kan alligevel bare collapse dem

2021-12-14 15:16 UTC, KasperHenningsen commented on DashboardBackend.Tests/HealthReportInfoParserTests.cs
> +        public List<HealthReportEntry> HostDataInput => new()
fair

2021-12-15 07:38 UTC, damniko commented on DashboardBackend/DataHandler.cs
> +                    let content = Regex.Replace(item.LogMessage, @"\u001b\[\d*;?\d+m", "")
svaret og klaret

2021-12-15 07:40 UTC, damniko commented on DashboardFrontend/ViewModels/ValidationReportViewModel.cs
> +            Executions = new(executions.ToList().Select(e => new ExecutionObservable(e, this)));
Prøvede med lock, men fik stadig samme exception - I dunno, men det virker med ToList() i hvert fald

2021-12-15 10:15 UTC, mirakst commented on DashboardFrontend/ViewModels/ValidationReportViewModel.cs
> +            Executions = new(executions.ToList().Select(e => new ExecutionObservable(e, this)));
det er fint, det var også den der løsning jeg fandt på stackoverflow

2021-12-15 10:19 UTC, mirakst approved these changes

2021-12-15 10:19 UTC, Mthage20 approved these changes

2021-12-15 10:19 UTC, KasperHenningsen approved these changes

2021-12-15 10:20 UTC, merged